spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# App Properties
sassedo.app.jwtSecret=finditSecretKey
sassedo.app.jwtExpirationMs=186144000000
feria.app.clientUrl=https://europos.bg
# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.config=classpath:log4j2.xml
#Hybernate Debug
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.transaction=DEBUG
# Mail Properties
spring.mail.host=mail.nineteen.bg
spring.mail.port=587
spring.mail.username=no-reply@nineteen.bg
spring.mail.password=NineteenLTD19!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Expose Prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus
# Enable the prometheus endpoint
management.endpoint.prometheus.enabled=true
# Optional: separate management port
management.server.port=8081
# Metrics configuration
management.prometheus.metrics.export.enabled=true
