package server.sassedo.model;

public enum GenericExceptionCode {
    // USER
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_NOT_STRONG,
    INCORRECT_PASSWORD,
    TOKEN_NOT_FOUND,
    TOKEN_EXPIRED,
    TOKEN_ALREADY_USED,
    INVALID_TOKEN,
    USER_ALREADY_VERIFIED,
    INVALID_VERIFICATION_CODE,
    NOT_VERIFIED,
    USER_BLOCKED,
    CONSENT_REQUIRED,
    INVALID_FILE,

    // COMMON
    HELPER_TEXT_NOT_FOUND,
    FAQ_NOT_FOUND,

    // BLOG
    BLOG_POST_NOT_FOUND,
    BLOG_IMAGE_NOT_FOUND,
    BLOG_SLUG_EXISTS,

    // CARD
    CARD_NOT_FOUND,

    // LISTING
    LISTING_NOT_FOUND,
    NOT_LISTING_OWNER,
    INVALID_LISTING_STATUS,
    LISTING_PHOTO_NOT_FOUND,

    // LOCATION
    COUNTRY_NOT_FOUND,
    CITY_NOT_FOUND,
    COUNTRY_ALREADY_EXISTS,
    CITY_ALREADY_EXISTS,

    // PROMOTION
    PROMOTION_PACKAGE_NOT_FOUND,
    PROMOTION_NOT_FOUND,
    LISTING_ALREADY_PROMOTED,
    PURCHASE_NOT_FOUND,
    PAYMENT_NOT_FOUND,
    PACKAGE_INACTIVE,
    NOT_PURCHASE_OWNER,
    NOT_PROMOTION_OWNER,
    INVALID_PROMOTION_REQUEST,
    PAYMENT_NOT_COMPLETED,

    // MESSAGING
    CONVERSATION_NOT_FOUND,
    NOT_CONVERSATION_PARTICIPANT,
    CANNOT_MESSAGE_SELF,
}
